language: cpp
compiler:
  - gcc
  - clang
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libncurses
  - sudo apt-get install -y libSDL libportmidi libsndfile libuv
  - git submodule init
  - git submodule update
script: make
